### PR TITLE
Card Update

### PR DESCRIPTION
**Pull request by meowteusz**
correct repo this time lol

### CODE REVIEW

**Comment by scolton99** [comment]
With all defaults set, I get this error trying to open FP and all pages load to blank white screen --
image

I suspect probably it's because I don't have the right settings set in my Footprints preferences? @mattryczek

**Comment by meowteusz** [comment]
Try setting your columns in this order?

image

Might have to switch the `get` functions to use the convoluted class names instead of traversing divs

**Comment by scolton99** [comment]
That fixed it -- I think the options are either that or try to load card layout and then if any errors are encountered, leave the original layout alone and provide some sort of banner that says "go to preferences and set your layout like this, then come back."

**Comment by meowteusz** [comment]
The former shouldn't be too difficult; I prefer the more portable/robust solution

**Comment by meowteusz** [comment]
@scolton99 Try it now with your original view. It should say "disabled" whenever it's missing info it needs instead of crashing.

**Comment by scolton99** [comment]
This all seems good to me -- the only other thing I'd ask is for a listing of all the columns that need to be shown in order to get full functionality, because otherwise it could be a little confusing. I'll like that to end up included in `README.md` and maybe also right on the `options.html` page?

**Comment by meowteusz** [comment]
Yep I'll start working on feature docs for this update. And do you mean you want a little paragraph of the columns required as static text on the options page?

**Comment by scolton99** [comment]
> Yep I'll start working on feature docs for this update. And do you mean you want a little paragraph of the columns required as static text on the options page?

Yeah the paragraph on the page would be good. Just because I don't want people to have to go to the README.md. And in preparation for the merge, could you make this version 5.0.0 in `manifest.json`?

**Comment by meowteusz** [comment]
Updated README and pushed the section with aesthetic changes to the top since it's the most immediately noticeable feature to users. Also need to fix a few bugs with search and login error pages.

**Comment by meowteusz** [comment]
@scolton99 ship it!!!

**Comment by meowteusz** [comment]
@scolton99 may i get a crumb of ship pls

**Comment by meowteusz** [comment]
@scolton99 I guess github wants the cards on by default, tried to edit through web GUI but it killed the commits again. Might be something due to migration from nuit-tsc acc? Can you merge this and then I can start another pull? Or you can just edit the `enableCards` line in js/options.js to `false` after merging this?

**Comment by scolton99** [comment]
Manually merged into `mateusz` branch

**Pull request closed without merging**
